# This workflow will do a clean installation of Node.js dependencies,
# cache/restore them, build the source code, and run tests across different versions of Node.js.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [19.x]  # Corrected the Node.js version
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy project files to /var/www/html
        run: cp -r /home/ubuntu/actions-runner/_work/pipeline/pipeline/* /var/www/html/

      - name: Change to the target directory
        run: cd /var/www/html

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the source code (if present)
        run: npm run build --if-present

      - name: Restart PM2 process (replace 'pipline' with the correct process name)
        run: pm2 restart pipline
